### ISSUE TITLE
Potential Crash Bug

### ISSUE THREAD

**Issue by zzyyzz1992** [liufan321/FFAutoLayout#1]
If I pass a empty array of type [UIView], the following functions crash:
public func ff_HorizontalTile(views: [UIView], insets: UIEdgeInsets) -> [NSLayoutConstraint]
public func ff_VerticalTile(views: [UIView], insets: UIEdgeInsets) -> [NSLayoutConstraint]

Here is a demo:
ff_HorizontalTile([], insets: UIEdgeInsets(top: 74, left: 10, bottom: 10, right: 10))
fatal error: Array index out of range
![screen shot 2015-06-28 at 6 48 28 pm](https://cloud.githubusercontent.com/assets/3894825/8396025/50f77c98-1dc6-11e5-944e-dd25f057bc3c.png)
I think this situation should be handled by this framework.

**Comment by liufan321** [comment]
加了个断言，感谢！
